In [266]:
import numpy as np

In [267]:
# NUMPY LIBRARAY

"""

Numpy is a powerful python library used for numerical computations and working with arrays.

Numpy stands for numerical python.

"""

# how to install numpy.?

!pip install numpy

# importing numpy library
import numpy as np

# how to check numpy version
np.__version__



'1.26.4'

In [268]:
# NUMPY ARRAY

"""

The basic data structure of numpy is array.

A Numpy is a collection of values with some data types stored together, which is similar to a list.

There are many types of numpy arrays: (similar to a matrix)
    1. 1D Array
    2. 2D Array
        ...

        ....
      N-Dimensional Array


Benifits of Numpy Arrays:

    1. Easy and Clean syntax for Element wise operations.(ie: Most of the computations in linear algebra and ML can be done through the aid of numpy arrays,
        especially in tensorflow)

    2. when you replace a for loop with a numpy function and see the speed improvement.


Major reasons behind numpy's faster computation:

    1. Numpy array is densely packed in memory due to its homogenous type.
    2. Numpy is able to divide a task into multiple sub tasks and process them paralelly.
    3. Numpy functions are implemented in C Language, which again makes it faster compared to python lists.


"""

# observe the speed of numpy when compared to python lists

l1 = range(1000000)

%timeit [i**2 for i in l1]

l2 = np.array(range(1000000))

%timeit [l2**2]







The slowest run took 4.89 times longer than the fastest. This could mean that an intermediate result is being cached.
179 ms ± 98.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
861 µs ± 65.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### from the above results, its evident that numpy computations are much faster compared to lists

In [269]:
# examples:

gadget_list = ["smartphone", "laptop", "headphones", "smartwatch", "tablet", "camera", "power bank",
               "gaming console", "Bluetooth speaker", "fitness tracker"]

sales_list =  [600,569,544,520,490,446,420,300,275,100 ]

production_list = [450,650,580,480,500,460,300,500,590,450 ]

len(gadget_list) == len(sales_list) == len(production_list)



True

In [270]:
# create 1 dimensional arrays from lists.

gadgets = np.array(gadget_list)

sales  = np.array(sales_list)

production = np.array(production_list)


# printing data types of lists

print(type(gadget_list))
print(type(gadget_list))
print(type(gadget_list))

# printing data types of created numpy arrays

print(type(gadgets))
print(type(sales))
print(type(production))

<class 'list'>
<class 'list'>
<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [271]:
# finding data types of numpy arrays

print(gadgets.dtype)
print(sales.dtype)
print(production.dtype)
print('\n')

# finding shape of numpy array

print(gadgets.shape)
print(sales.shape)
print(production.shape)
print('\n')

# finding dimensions of arrays

print(gadgets.ndim)
print(sales.ndim)
print(production.ndim)

<U17
int64
int64


(10,)
(10,)
(10,)


1
1
1


In [272]:
# accessing and slicing elements in numpy arrays

"""

similar to python data types, numpy also follows same convention for indexing and slicing elements.

"""

print(gadgets[0])

print(gadgets[1:6])

print(gadgets[::-1])

print(gadgets[6:-1])

print(len(gadgets))

smartphone
['laptop' 'headphones' 'smartwatch' 'tablet' 'camera']
['fitness tracker' 'Bluetooth speaker' 'gaming console' 'power bank'
 'camera' 'tablet' 'smartwatch' 'headphones' 'laptop' 'smartphone']
['power bank' 'gaming console' 'Bluetooth speaker']
10


In [273]:
# finding max and minimum values in a numpy array.

"""
argmax returns the index or position of value in an array.

similarly, argmin returns the index or position of value in an array.

"""
# finding item/goods with highest sales
best_selling_gadget_index = np.argmax(sales)

best_selling_gadget = gadgets[best_selling_gadget_index]

print("Best Selling Gadget is: ", best_selling_gadget)

print("\n")

# finding item/goods with lowest sales
least_selling_gadget_index = np.argmin(sales)

least_selling_gadget = gadgets[least_selling_gadget_index]

print("Least Selling Gadget is: ", least_selling_gadget)

print("\n")

# finding item that has produced highest
most_produced_index = np.argmax(production)

most_produced_item = gadgets[most_produced_index]

print("Item with Highest Production Units: ", most_produced_item)

print("\n")

# finding items that has least production rate
least_produced_index = np.argmin(production)

least_produced_item = gadgets[least_produced_index]

print("Item wuth Least Production rate is: ", least_produced_item)




Best Selling Gadget is:  smartphone


Least Selling Gadget is:  fitness tracker


Item with Highest Production Units:  laptop


Item wuth Least Production rate is:  power bank


In [274]:
# what is the ratio of sales and production for top 3 selling items.

"""

for a optimised ratio: sales < production

"""

# given an array, argsort will returns an array of indices that represent the order of elements when sorted in ascending order.

top_3_selling_indices = np.argsort(sales)[-3:]

sales_to_production_ratio_top3 = sales[top_3_selling_indices] / production[top_3_selling_indices]

print("Sales to production ratio for top 3 Selling items are: ")

for index in top_3_selling_indices:
    print(f"{gadget_list[index]} : {sales_to_production_ratio_top3[index]}")

Sales to production ratio for top 3 Selling items are: 
headphones : 1.3333333333333333
laptop : 0.8753846153846154
smartphone : 0.9379310344827586


In [275]:
# now we want to have seperate lists for under procured and over procured goods lists.

"""

for this we need to check gadgets, where:
    sales < production --> for over procured.
    sales > production --> for under procured.

"""



'\n\nfor this we need to check gadgets, where:\n    sales < production --> for over procured.\n    sales > production --> for under procured.\n\n'

In [276]:
# example to undertsand how greater than and lesser than symbols works.

a = np.array([1,32,4,5,6,2,34,25])

b = np.array([2,2,0,51,4,0,54,26])

print(a > b)

[False  True  True False  True  True False False]


### we got boolean as an array for our output.

observe:
    elements which satisfied the condition are returned as "TRUE",
    meanwhile others as "FALSE".

This is called a MASKED Array



In [277]:
c = a[a > b]

print(c)

[32  4  6  2]


In [278]:
# check for products that are under procured and over procured.

"""

if sales > production, then under procured

if sales < production, then over procured.

"""

under_procured_gadgets = gadgets[sales > production]

over_procured_gadgets = gadgets[sales < production]


print("Over Procured Gadgets are: ", over_procured_gadgets)
print("\n")
print("Under Procured Gadgets are: ", under_procured_gadgets)

Over Procured Gadgets are:  ['laptop' 'headphones' 'tablet' 'camera' 'gaming console'
 'Bluetooth speaker' 'fitness tracker']


Under Procured Gadgets are:  ['smartphone' 'smartwatch' 'power bank']


In [279]:
# Producing certain gadgets less in number makes sense, then how to boost the sales of under selling products

"""

1. Marketing push?
2. Bundling offers?
3. Special Promotions?

but for which products?

"""


'\n\n1. Marketing push?\n2. Bundling offers?\n3. Special Promotions?\n\nbut for which products?\n\n'

### We can plan to invest more on advertising for the least selling gadgets in the market in order to increase the sales of overall optimised prices at stores

In [280]:
# gadgets with lower sales for optimisation

# NP.MEAN() is a statistical function used to get the average value for a given array
lower_sales_gadgets = gadgets[sales < np.mean(sales)]

print(lower_sales_gadgets)



['power bank' 'gaming console' 'Bluetooth speaker' 'fitness tracker']


### let's see about 2D Arrays

In [281]:
# example:

# this is list of tuples, comprising height (inches) and weight (pounds) for all players.

players_List =  [(74, 180), (74, 215), (72, 210), (72, 210), (73, 188), (69, 176), (69, 209),
           (71, 200), (76, 231), (71, 180), (73, 188), (73, 180), (74, 185), (74, 160),
           (69, 180)]


print(type(players_List))
print("\n")
print(players_List)
print("\n")
print(len(players_List))

print(type(players_List[2]))

<class 'list'>


[(74, 180), (74, 215), (72, 210), (72, 210), (73, 188), (69, 176), (69, 209), (71, 200), (76, 231), (71, 180), (73, 188), (73, 180), (74, 185), (74, 160), (69, 180)]


15
<class 'tuple'>


In [282]:
# creating numpy array for the given list

players = np.array(players_List)

print(players)
print("\n")
print(players.shape)
print("\n")
print(players.ndim)
print("\n")
print(players.dtype)

[[ 74 180]
 [ 74 215]
 [ 72 210]
 [ 72 210]
 [ 73 188]
 [ 69 176]
 [ 69 209]
 [ 71 200]
 [ 76 231]
 [ 71 180]
 [ 73 188]
 [ 73 180]
 [ 74 185]
 [ 74 160]
 [ 69 180]]


(15, 2)


2


int64


In [283]:
# accessing first players height and weight

first_player_tuple = players[0]

print(first_player_tuple)

height = players[0][0]

weight = players[0][1]

print(height, weight)

[ 74 180]
74 180


In [284]:
# accesing 2nd and 4th players info.

second_person_height = players[1][0]
second_person_weight = players[1][1]

print(second_person_height, second_person_weight
      )

print("\n")

fourth_person_height = players[3][0]
fourth_Players_weight = players[3][1]

print(fourth_person_height, fourth_Players_weight)

74 215


72 210


In [285]:
players[1:5]

array([[ 74, 215],
       [ 72, 210],
       [ 72, 210],
       [ 73, 188]])

In [286]:
# how to  fetch players height only
# this syntax means fetch all the values
players[::]

array([[ 74, 180],
       [ 74, 215],
       [ 72, 210],
       [ 72, 210],
       [ 73, 188],
       [ 69, 176],
       [ 69, 209],
       [ 71, 200],
       [ 76, 231],
       [ 71, 180],
       [ 73, 188],
       [ 73, 180],
       [ 74, 185],
       [ 74, 160],
       [ 69, 180]])

In [287]:
# players[rows:columns]

players[:,0]

array([74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69])

In [288]:
players[:,1]

array([180, 215, 210, 210, 188, 176, 209, 200, 231, 180, 188, 180, 185,
       160, 180])

In [289]:
players_height = players[:,0]

players_weight = players[:,1]

print("Players Heights are: ", players_height)
print("\n")
print("Players Weights are: ", players_weight)

Players Heights are:  [74 74 72 72 73 69 69 71 76 71 73 73 74 74 69]


Players Weights are:  [180 215 210 210 188 176 209 200 231 180 188 180 185 160 180]


In [290]:
# how to fetch only first 5 players weight

players[0:5,1]

array([180, 215, 210, 210, 188])

In [291]:
# height of 10th player
players[9,0]

71

In [292]:
# converting heights to metres and weights to kgs

players = players * [0.0254, 0.453592]

In [293]:
players

array([[  1.8796  ,  81.64656 ],
       [  1.8796  ,  97.52228 ],
       [  1.8288  ,  95.25432 ],
       [  1.8288  ,  95.25432 ],
       [  1.8542  ,  85.275296],
       [  1.7526  ,  79.832192],
       [  1.7526  ,  94.800728],
       [  1.8034  ,  90.7184  ],
       [  1.9304  , 104.779752],
       [  1.8034  ,  81.64656 ],
       [  1.8542  ,  85.275296],
       [  1.8542  ,  81.64656 ],
       [  1.8796  ,  83.91452 ],
       [  1.8796  ,  72.57472 ],
       [  1.7526  ,  81.64656 ]])

In [294]:
# fetching height and weights of players, whose height is above 1.8 metres

# by using masking concept we can achieve this

height_in_mtrs = players[:,0]

In [295]:
height_in_mtrs

array([1.8796, 1.8796, 1.8288, 1.8288, 1.8542, 1.7526, 1.7526, 1.8034,
       1.9304, 1.8034, 1.8542, 1.8542, 1.8796, 1.8796, 1.7526])

In [296]:
greater_height = height_in_mtrs[height_in_mtrs > 1.8]

In [297]:
greater_height

array([1.8796, 1.8796, 1.8288, 1.8288, 1.8542, 1.8034, 1.9304, 1.8034,
       1.8542, 1.8542, 1.8796, 1.8796])

In [298]:
print(len(height_in_mtrs))
len(greater_height)

15


12

In [299]:
# find count of players whose weight is greater than or equal to 80 kgs

weight_in_Kgs = players[:,1]

In [300]:
weight_in_Kgs

array([ 81.64656 ,  97.52228 ,  95.25432 ,  95.25432 ,  85.275296,
        79.832192,  94.800728,  90.7184  , 104.779752,  81.64656 ,
        85.275296,  81.64656 ,  83.91452 ,  72.57472 ,  81.64656 ])

In [301]:
greater_weight = weight_in_Kgs[weight_in_Kgs >= 80]

In [302]:
greater_weight

array([ 81.64656 ,  97.52228 ,  95.25432 ,  95.25432 ,  85.275296,
        94.800728,  90.7184  , 104.779752,  81.64656 ,  85.275296,
        81.64656 ,  83.91452 ,  81.64656 ])

In [303]:
print(len(weight_in_Kgs))
len(greater_weight)

15


13

In [304]:
# fetch player details whose weight is gretaer than 80 and height is greater than 1.8 metres

filtered_players = players[(players[:, 0] > 1.80) & (players[:, 1] > 95)]

In [305]:
filtered_players

array([[  1.8796  ,  97.52228 ],
       [  1.8288  ,  95.25432 ],
       [  1.8288  ,  95.25432 ],
       [  1.9304  , 104.779752]])

In [306]:
# other ways of creating numpy arrays

np.zeros((5,6),dtype='int')

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [307]:
np.ones((6,4),dtype='int')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [308]:
np.ones(9, dtype='float')

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [309]:
# creating an array of a defined shape, with only a specific value

np.full([15,6],9)

array([[9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9]])

In [310]:
# creating an array with increments of fixed step size.

"""

np.arange(start, stop, step)

this can take float values as well by adjusting the step size.

"""

np.arange(0,15,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [311]:
np.arange(5,25,2.5)

array([ 5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5])

In [312]:
# create evenly spaced numbers over a specific interval.

"""

np.linspace(start, stop, num) over a specific interval.


"""

np.linspace(1,2,3)


array([1. , 1.5, 2. ])

In [313]:
np.linspace(1,15,5)

array([ 1. ,  4.5,  8. , 11.5, 15. ])

In [314]:
# example

a = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[91,100,110,120],[34,56,33,22],[1,5,6,78]]

a = np.array(a)

In [315]:
print(a)
print("\n"
)
print(a.ndim)
print("\n")
print(a.shape)

[[  1   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]
 [ 91 100 110 120]
 [ 34  56  33  22]
 [  1   5   6  78]]


2


(6, 4)


In [316]:
# printing all rows for column 1
a[:,0]

array([ 1,  5,  9, 91, 34,  1])

In [317]:
# printing all columns for row 1
a[0,:]

array([1, 2, 3, 4])

In [318]:
# printing subsection from row 3 to row 5

a[2:6,1:]

array([[ 10,  11,  12],
       [100, 110, 120],
       [ 56,  33,  22],
       [  5,   6,  78]])

### sales are surging, we want to ensure that increased demand is met. so we have decided to increase the production of all sales by 20%

In [319]:
sales

array([600, 569, 544, 520, 490, 446, 420, 300, 275, 100])

In [320]:
production

array([450, 650, 580, 480, 500, 460, 300, 500, 590, 450])

In [321]:
production = production.astype(float)

production *= 1.2

In [322]:
production

array([540., 780., 696., 576., 600., 552., 360., 600., 708., 540.])

In [323]:
# it is not possible to produce goods in decimal points, instead it should be an integer

production = production.astype(int)

production

array([540, 780, 696, 576, 600, 552, 360, 600, 708, 540])

In [324]:
# we have recieved a new shipment of gadgets and updated your inventory

# to ensure accuracy in inventory, you have to check if the new production list matches the original one.


"""

element wise comparision must be done

np.array_equal() helps to achieve this.

"""

a1 = np.array([1,2,6])

b1 = np.array([5,6,9])

print(all(a1==b1))

print(any(a1==b1))

False
False


In [325]:
np.array_equal(a1,b1)

False

In [326]:
new_production_list = [648, 936, 835, 691, 720, 662, 432, 720, 849, 648] # New list

new_production = np.array(new_production_list)

print(np.array_equal(production, new_production))

False


In [327]:
# calculating available stock for each gadget

available_stock = production - sales

print(available_stock)

[-60 211 152  56 110 106 -60 300 433 440]


## MATRIX MULTIPLICATION

In [328]:
x = [[1,2],[3,4]]

y = [[1,3],[1,5]]

z = np.dot(x,y)

In [329]:
z

array([[ 3, 13],
       [ 7, 29]])

In [330]:
# dot product on one dimensional array

a3 = np.array([1,5,9])

b3 = np.array([2,4,6])

c3 = np.dot(a3,b3)

In [331]:
c3

76

In [332]:
# now we have market factors, which affect the sales

market_factors = np.array([[0.5], [0.8], [0.6], [0.7], [0.9], [0.4], [0.3], [0.5], [0.7], [0.6]])

weighted_sales = np.dot(sales, market_factors)

weighted_sales

array([2593.5])

### to evaluate store's performance, we want to calculate mean, variance, std .deviation of sales data. providinf statistical overview for sales trends.

In [333]:
# this can be achieved by numpy statistical operators

print(np.mean(sales))

print(np.var(sales))

print(np.std(sales))

print(np.cumsum(sales))



426.4
22296.840000000004
149.32126439325378
[ 600 1169 1713 2233 2723 3169 3589 3889 4164 4264]


In [334]:
# how to perform statistical operators for a 2D Array

"""

we have two axis in a 2D array, axis = 0 represents columns

and axis=1 represents rows.

"""

# ex:

mat = np.array([[1,2,3,4],[5,6,7,8]])

print(mat)

[[1 2 3 4]
 [5 6 7 8]]


In [335]:
# calculating mean values for all columns
mat = mat.astype(float)
np.mean(mat, axis=0)

array([3., 4., 5., 6.])

In [336]:
# calculating mean values across rows

np.mean(mat, axis=1)

array([2.5, 6.5])

In [337]:
marks = np.array([40,51,62,73,82,92])

names = np.array(["ram","shyam","mohan","vijay","aman","vishal"])

students_scored_odd_number_marks = names[marks % 2 != 0]

In [338]:
students_scored_odd_number_marks

array(['shyam', 'vijay'], dtype='<U6')

In [339]:
# to plan for future discounts, we have to sort sales data in ascending order.

"""

this helps in identifying which gadgets might benifit most from promotional pricing.

np.sort() returns array with values in ascending order


"""

sorted_sales = np.sort(sales)

sorted_sales

array([100, 275, 300, 420, 446, 490, 520, 544, 569, 600])

In [340]:
mat

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [341]:
np.sort(mat,axis=0)

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [342]:
# if we want to sort, but in descending order

a4 = [1,0,4,5,6]

b4 = sorted(a4,reverse=True)

print(b4)

[6, 5, 4, 1, 0]


## Reshaping the arrays

In [343]:
print(sales )

print(sales.shape)

[600 569 544 520 490 446 420 300 275 100]
(10,)


In [344]:
reshaped_sales = sales.reshape(5,2)

reshaped_sales

array([[600, 569],
       [544, 520],
       [490, 446],
       [420, 300],
       [275, 100]])

In [345]:
reshaped_sales1 = sales.reshape(3,4)

ValueError: cannot reshape array of size 10 into shape (3,4)

## shape must be choosen accordingly, or else it wil throw an error like this

In [ ]:
reshaped_sales2 = sales.reshape(2,5)

reshaped_sales2

### RESIZE

In [346]:
# Numpy also has resize function, similar to reshape() function

"""

the only difference being resize() function changes the original array instead of creating a new copy.


"""


'\n\nthe only difference being resize() function changes the original array instead of creating a new copy.\n\n\n'

In [347]:
# TRANSPOSE

a5 = np.array([[9,5,7],[6,3,10]])
a5

array([[ 9,  5,  7],
       [ 6,  3, 10]])

In [348]:
print(a5.shape)


(2, 3)


In [349]:
print(a5.ndim)

2


In [350]:
b5 = a5.T

print(b5)
print("\n")
print(b5.shape)
print("\n")

print(b5.ndim)

[[ 9  6]
 [ 5  3]
 [ 7 10]]


(3, 2)


2


In [351]:
transposed_sales = reshaped_sales.T

print(reshaped_sales.shape)

print(transposed_sales.shape)

(5, 2)
(2, 5)


In [352]:
reshaped_sales

array([[600, 569],
       [544, 520],
       [490, 446],
       [420, 300],
       [275, 100]])

In [353]:
transposed_sales

array([[600, 544, 490, 420, 275],
       [569, 520, 446, 300, 100]])

In [354]:
# after the analysis, we want to flatten the matrix back to 1D AArray for reporting.

"""

with the aid of Flatten function, this can be done.

Flatten function converts a multi dimensional array into a 1D array.

the original array does not change, because the flatten function makes a deep copy. instead of over writing.

"""

a6 = np.array([[1,2,3],[4,5,6],[7,8,9]])

a6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [355]:
flattened_a6 = a6.flatten()

print(a6.shape)

print(flattened_a6.shape)

(3, 3)
(9,)


In [356]:
flattened_sales = transposed_sales.flatten()

flattened_sales

array([600, 544, 490, 420, 275, 569, 520, 446, 300, 100])

In [357]:
flattened_sales.shape

(10,)

In [358]:
# RAVEL FUNCTION

"""

Numpy also has ravel() function which is similar to flatten function.

the only difference being, ravel() function changes the original array because it makes a shallow copy.

whereas flatten() makes a deep copy.


"""



'\n\nNumpy also has ravel() function which is similar to flatten function.\n\nthe only difference being, ravel() function changes the original array because it makes a shallow copy.\n\nwhereas flatten() makes a deep copy.\n\n\n'

In [359]:
# combine sales and production data into a single array for comparision

"""

in the last step you bring togther sales and production data t make comprehensive and comparitive analyses for future strategy formulation.

This can be solved using vstack function in numpy.

similarly, hstack() function returns an array, where arrays provided as arguments are stacked horizontaly beside each other., by stacking
this way number of rows stay same, while the number of columns increases.


"""



'\n\nin the last step you bring togther sales and production data t make comprehensive and comparitive analyses for future strategy formulation.\n\nThis can be solved using vstack function in numpy.\n\nsimilarly, hstack() function returns an array, where arrays provided as arguments are stacked horizontaly beside each other., by stacking \nthis way number of rows stay same, while the number of columns increases.\n\n\n'

In [360]:
a7 = np.array([[1,2,3],[4,5,6]])

b7 = np.array([[7,8,9],[0,0,1]])

print("a7 array is")
print(a7)
print(" ")
print("b7 array is")
print(b7)

a7 array is
[[1 2 3]
 [4 5 6]]
 
b7 array is
[[7 8 9]
 [0 0 1]]


In [361]:
c7 = np.vstack([a7,b7])

In [362]:
c7

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 0, 1]])

In [363]:
combined_data_vertical = np.vstack([sales, production])

combined_data_vertical

array([[600, 569, 544, 520, 490, 446, 420, 300, 275, 100],
       [540, 780, 696, 576, 600, 552, 360, 600, 708, 540]])

In [364]:
# splitting array

a8 = np.array([1,2,3,4,5,6])

np.split(a8,2)

[array([1, 2, 3]), array([4, 5, 6])]

In [365]:
a9 = np.array([1,2,3,4,5,6])

np.split(a9,4)

ValueError: array split does not result in an equal division

In [377]:
a10 = np.array([1,2,3,4,5,6])

np.split(a10,6)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]

In [378]:
x2 = np.arange(16.0)

np.split(x2, np.array([3,6,9]))

[array([0., 1., 2.]),
 array([3., 4., 5.]),
 array([6., 7., 8.]),
 array([ 9., 10., 11., 12., 13., 14., 15.])]

In [379]:
# how to split array vertically..?

a11 = np.array([[1,2,3],[4,5,6],[0,1,3],[4,1,3]])

print(a11)

[[1 2 3]
 [4 5 6]
 [0 1 3]
 [4 1 3]]


In [380]:
b11 = np.vsplit(a11, 2)

In [381]:
b11

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[0, 1, 3],
        [4, 1, 3]])]

In [382]:
"""

for vsplit to work, array must be atleast 2 dimensional.

the number of rows must be divisible by the number of splits you want to perform.

"""

'\n\nfor vsplit to work, array must be atleast 2 dimensional.\n\nthe number of rows must be divisible by the number of splits you want to perform.\n\n'

In [383]:
x3 = np.arange(16)

In [384]:
x3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [385]:
x3.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [386]:
# CONCATENATE

"""

concatenate function in numpy joins a sequence of arrays along an existing axis.

"""


'\n\nconcatenate function in numpy joins a sequence of arrays along an existing axis.\n\n'

In [387]:
a12 = np.array([[1,2,4],[4,5,6]])

b12 = np.array([[0,1,2],[3,4,6]])

print(a12)
print(" ")
print(b12)


[[1 2 4]
 [4 5 6]]
 
[[0 1 2]
 [3 4 6]]


In [388]:
c12 = np.concatenate((a12, b12))

In [389]:
c12

array([[1, 2, 4],
       [4, 5, 6],
       [0, 1, 2],
       [3, 4, 6]])

In [390]:
c12 = np.concatenate((a12,b12),axis=0)
c12

array([[1, 2, 4],
       [4, 5, 6],
       [0, 1, 2],
       [3, 4, 6]])

In [391]:
c12 = np.concatenate((a12,b12),axis=1)

c12


array([[1, 2, 4, 0, 1, 2],
       [4, 5, 6, 3, 4, 6]])

In [392]:
# TRACE

"""

trace function computes the sum of diagonal elements in a square matrix.

"""


'\n\ntrace function computes the sum of diagonal elements in a square matrix.\n\n'

In [393]:
a13 = np.array([[1,2,3],[4,5,6],[0,1,3]])
print(a13)

[[1 2 3]
 [4 5 6]
 [0 1 3]]


In [394]:
a13_trace = np.trace(a13)

a13_trace

9

In [395]:
# calculating trace for secondary diagonal

a14_trace = np.trace(a13[::-1])

a14_trace

8

# RANDOM

In [396]:
"""

random function in numpy generates random numbers.

"""

'\n\nrandom function in numpy generates random numbers.\n\n'

In [397]:
np.random.randint(6)

4

In [398]:
np.random.randint(100,size=(5))

array([91, 62, 61, 99, 74])

In [399]:
np.random.randint(10,size=(10))

array([7, 1, 4, 7, 1, 9, 2, 2, 2, 3])

In [400]:
np.random.randint(10,size=(3,3))

array([[2, 8, 9],
       [9, 2, 7],
       [8, 2, 2]])

In [401]:
np.random.randint(10,size=(5,4))

array([[4, 6, 5, 8],
       [0, 9, 5, 6],
       [2, 4, 0, 2],
       [0, 1, 8, 2],
       [2, 9, 4, 5]])

In [402]:
# prints random number betwen 0 and 1
np.random.rand()

0.375295363834814

In [403]:
np.random.rand(3,4)

array([[0.74533037, 0.8224802 , 0.10037594, 0.00709342],
       [0.04697152, 0.73133398, 0.59474972, 0.85495919],
       [0.38008746, 0.9128762 , 0.17336551, 0.0502582 ]])

In [404]:
np.random.choice([11,5,4,8,69])

4

In [405]:
np.random.choice([3,5,6,78,8],size=(3,5))

array([[ 5,  6,  8, 78,  6],
       [ 6, 78, 78,  8,  8],
       [ 3,  3,  6,  8,  6]])

## WHERE

In [406]:
"""

The np.where function in NumPy is a versatile tool used for array manipulation. It can act as a conditional selector,
a means to find indices where conditions are true, or as a way to replace elements based on a condition.

"""

'\n\nThe np.where function in NumPy is a versatile tool used for array manipulation. It can act as a conditional selector, \na means to find indices where conditions are true, or as a way to replace elements based on a condition.\n\n'

In [407]:
a15 = np.random.rand(2,3)

print(a15)

[[0.39199989 0.42101435 0.84756168]
 [0.65115536 0.93863021 0.91751409]]


In [408]:
b15 = np.where( a15>0.5, a15, 0)

print(b15)

[[0.         0.         0.84756168]
 [0.65115536 0.93863021 0.91751409]]


In [409]:
b15 = np.where( a15>0.5, a15*100, 1)

print(b15)

[[ 1.          1.         84.75616779]
 [65.11553645 93.86302092 91.75140911]]


In [410]:
print(a15)

[[0.39199989 0.42101435 0.84756168]
 [0.65115536 0.93863021 0.91751409]]


In [411]:
b15 = np.where(a15>0.5)

print(b15)

(array([0, 1, 1, 1]), array([2, 0, 1, 2]))


### CASE STUDY

In [412]:
# Customer data (height in inches, weight in pounds)
customer_list = [(74, 180), (74, 215), (72, 210), (72, 210), (73, 188), (69, 176), (69, 209),
                 (71, 200), (76, 231), (71, 180), (73, 188), (73, 180), (74, 185), (74, 160),
                 (69, 180)]

customer = np.array(customer_list)

In [413]:
customer

array([[ 74, 180],
       [ 74, 215],
       [ 72, 210],
       [ 72, 210],
       [ 73, 188],
       [ 69, 176],
       [ 69, 209],
       [ 71, 200],
       [ 76, 231],
       [ 71, 180],
       [ 73, 188],
       [ 73, 180],
       [ 74, 185],
       [ 74, 160],
       [ 69, 180]])

In [414]:
customer.shape

(15, 2)

In [415]:
cust_height = customer[:,0]

cust_height

array([74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69])

In [416]:
# converting height to meter

cust_height = cust_height * 0.0254

cust_height

array([1.8796, 1.8796, 1.8288, 1.8288, 1.8542, 1.7526, 1.7526, 1.8034,
       1.9304, 1.8034, 1.8542, 1.8542, 1.8796, 1.8796, 1.7526])

In [417]:
cust_weight = customer[:,1]

In [418]:
cust_weight

array([180, 215, 210, 210, 188, 176, 209, 200, 231, 180, 188, 180, 185,
       160, 180])

In [419]:
cust_weight = cust_weight * 0.453592

cust_weight

array([ 81.64656 ,  97.52228 ,  95.25432 ,  95.25432 ,  85.275296,
        79.832192,  94.800728,  90.7184  , 104.779752,  81.64656 ,
        85.275296,  81.64656 ,  83.91452 ,  72.57472 ,  81.64656 ])

In [420]:
bmi = cust_weight / cust_height**2

In [421]:
bmi

array([23.11037639, 27.60406069, 28.48080465, 28.48080465, 24.80333518,
       25.99036864, 30.86356276, 27.89402921, 28.11789135, 25.10462629,
       24.80333518, 23.7478741 , 23.75233129, 20.54255679, 26.58105883])

In [422]:
bmi.shape

(15,)